modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/EnvyWare/BetterDexRewards/issues"

[[mods]]
modId="pixelmonoverlay"
version="1.2.0"
displayName="PixelmonOverlay Forge"
displayURL="https://github.com/EnvyWare"
credits="https://github.com/EnvyWare"
authors="https://github.com/EnvyWare"
description='''
Adds overlays
'''

[[dependencies.pixelmonoverlay]]
modId="forge"
mandatory=true
versionRange="[48.0.22,)"
ordering="NONE"
side="BOTH"

[[dependencies.pixelmonoverlay]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"